name: On merging into feature branch
on:
  push:
    branches:
      - "features/**"
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - "features/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Preparing app's name"
        run: echo "Preparing pushed app's name"
      - name: "Preparing to run test"
        uses: "./.github/workflows/template-test.yml"
