name: test-action
on:
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      output-file: ${{ steps.publish.outputs.script-files }}
    steps:
      - name: Print hello from github action
        run: echo "Hello from github action"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install Bunjs
        run: npm install -g bun
      - name: Get Bun's version
        run: bun -v
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: Publish package name
        id: publish
        run: find ./*.json -type f -execdir echo 'script-files={}'>> $GITHUB_OUTPUT ';'
      - name: Cache Dependency
        uses: actions/cache@v4
        with:
          path: node_modules
          key: bun-cache-${{ hashFiles('**/bun.lock') }}
      - name: Install Dependencies
        if: steps.publish.outputs.cache-hit != 'true'
        run: bun i --frozen-lockfile
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            package.json
            bun.lock

  deploy:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install Bunjs
        run: npm install -g bun
      - name: Get Bun's version
        run: bun -v
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: List files
        run: ls -la
      - name: Get Publish Param
        run: echo "${{ needs.setup.outputs.output-file }}"
      - name: Cache Dependency
        id: deploy
        uses: actions/cache@v4
        with:
          path: ~/.bun
          key: bun-cache-${{ hashFiles('**/bun.lock') }}
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        if: steps.deploy.outputs.cache-hit != 'true'
        run: bun i --frozen-lockfile
      - name: Deploy
        run: echo "Deploying......"

  deploy_import:
    uses: ./.github/workflows/deploy-template.yml
