name: Setup Runner
on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: latest
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install Bunjs
        run: |
          npm install -g bun
          bun -v
      - name: Install Turborepo
        run: |
          bun i -g turbo
          export PATH="/home/runner/.bun/bin:$PATH"
