name: test-action
on: push
jobs:
  first-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello from github action
        run: echo "Hello from github action"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install Bunjs
        run: npm install -g bun
      - name: Get Bun's version
        run: bun -v
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: List out files
        run: |
          echo "Showing all files"
          ls -la
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            package.json
            bun.lock
